name=ESP32_Multitasking_Network_Suite
version=1.0.4
includes=MultitaskingServers.h
author=Bojan Jurca
maintainer=Bojan Jurca <bojan@gmail.com>
sentence=Multitasking HTTP, HTTPS, FTP, Telnet servers and thread-safe NTP, HTTP, HTTPS, SMTP clients
paragraph=True multitasking architecture - each server runs in its own FreeRTOS task for high concurrency and responsiveness.
category=Communication
url=https://github.com/BojanJurca/Multitasking-Http-Ftp-Telnet-Ntp-Smtp-Servers-and-clients-for-ESP32-Arduino-Library
architectures=esp32
depends=LightweightSTL,ThreadSafePing,ThreadSafeFS,cronDaemon,wolfssl
license=MIT